# -*- coding: utf-8 -*-
"""Day 16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sADGcqgZTYzLFQ0apNQUsGZNnJ_9REQJ

## FEATURE ENGINEERING AND DATA PREPROCESSING
"""

import pandas as pd
df=pd.DataFrame({'dob':['1995-03-15','1988-11-02','2001-07-20']})
df['dob']=pd.to_datetime(df['dob'])
df['age']=2024-df['dob'].dt.year
df['birth_month']=df['dob'].dt.month
df['birth_day']=df['dob'].dt.day_name()
bins=[0,28,44,60,100]
labels=['genz','millineal','genx','alpha']
df['generation']=pd.cut(df['age'],bins=bins,labels=labels)
print(df[['age','birth_month','birth_day','generation']])

from sklearn.preprocessing import LabelEncoder
import pandas as pd
df['purchased']=['yes','no','yes']
le=LabelEncoder()
df['purchased']=le.fit_transform(df['purchased'])
# Add a 'size' column to the DataFrame before using it
df['size']=['small','medium','large']
size_order={'small':0,'medium':2,'large':6}
df['size_enc']=df['size'].map(size_order)
print(df[['purchased','size','size_enc']])

import pandas as pd
df = pd.DataFrame({'city': ['Delhi', 'Mumbai', 'Chennai', 'Delhi']})
df_encoded = pd.get_dummies(df, columns=['city'], dtype=int)
print(df_encoded)

print("--------------")
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, drop='first')
encoded = ohe.fit_transform(df[['city']])

print(encoded)

import pandas as pd
import numpy as np
df=pd.DataFrame({
    'feature_A':[1,2,np.nan,4,5],
    'feature_B':["x","y","z",np.nan,"w"],
     'feature_c':[10.5,np.nan,12.3,13.0,np.nan],
})
print("missing value count percolumn")
print(df.isnull().sum())
print('percentage missing per column:')
print(df.isnull().mean()*100)

from sklearn.impute import SimpleImputer
import numpy as np
numeric_cols = ['feature_A', 'feature_c'] # Corrected 'feature_C' to 'feature_c'
num_imputer = SimpleImputer(strategy='median')

df[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])

categorical_cols = ['feature_B']
cat_imputer = SimpleImputer(strategy='most_frequent')

df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])


print('Total missing values after imputation:', df.isnull().sum().sum()) # Should print 0
print('\nDataFrame after imputation:')
print(df)

# Method 1: IQR (interquartile range) — robust to distribution shape
# Using 'feature_A' as a numerical column for demonstration
Q1 = df['feature_A'].quantile(0.25)
Q3 = df['feature_A'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Keep only rows within bounds
df_clean_iqr = df[(df['feature_A'] >= lower) & (df['feature_A'] <= upper)]
print("DataFrame after IQR outlier removal on 'feature_A':")
print(df_clean_iqr)
print('\n')

# Method 2: Z-score — works well for normally distributed data
from scipy import stats
# Using 'feature_A' for demonst ration
z_scores = stats.zscore(df['feature_A'])
df_clean_zscore = df[abs(z_scores) < 3] # remove rows where |z| > 3
print("DataFrame after Z-score outlier removal on 'feature_A' (threshold 3):")
print(df_clean_zscore)

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Assuming 'df' is the DataFrame from previous steps
# For demonstration, let's define X and y from the existing 'df'
X = df[['feature_A', 'feature_c']] # Corrected 'feature_C' to 'feature_c'
# Create a dummy target variable 'y' for classification example
# e.g., if feature_A is greater than its median, classify as 1, else 0
y = (df['feature_A'] > df['feature_A'].median()).astype(int)

# Step 1: split data BEFORE building the pipeline
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 2: define the pipeline (a list of (name, transformer) tuples)
pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')), # fill NaNs
    ('scaler', StandardScaler()), # scale features
    ('model', LogisticRegression(random_state=42)), # train classifier
])

# Step 3: fit ONLY on training data — one call does everything
pipe.fit(X_train, y_train)

# Step 4: evaluate — the pipeline automatically transforms X_test
# using parameters learned from X_train (no leakage!)
print('Accuracy:', pipe.score(X_test, y_test))

# Predict new data in production — just one call
# For demonstration, create a sample X_new based on df's columns
X_new = pd.DataFrame({
    'feature_A': [6.0, np.nan, 8.0],
    'feature_c': [15.0, 16.0, np.nan] # Corrected 'feature_C' to 'feature_c'
})
predictions = pipe.predict(X_new)
print('Predictions for new data:', predictions)